spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: task-management
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: ${DB_URL:jdbc:postgresql://localhost:5432/task-management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:omarqwer1}
    driverClassName: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET:T4PaTy3kpvXi9hgX7tyANVWts3NV6fFcX3XiRmlEO8kL4481mw8MQfi9to2}